<Project>
  <PropertyGroup>
    <Configuration>Release</Configuration>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugType>none</DebugType>
    <PublishDir>..\publish\$(RuntimeIdentifier)\</PublishDir>
  </PropertyGroup>

  <Target Name="ExcludeSymbolsAndDocsFromPublish" AfterTargets="ComputeResolvedFilesToPublishList">
    <ItemGroup>
      <ResolvedFileToPublish Remove="@(ResolvedFileToPublish)" Condition="'%(Extension)' == '.pdb' or '%(Extension)' == '.xml'" />
    </ItemGroup>
  </Target>
</Project>
